version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_NODES=redis://redis1:7070,redis://redis2:7071 
      - DEBUG=true
    depends_on:
      - redis1
      - redis2

  redis1:
    image: redis:7
    ports:
      - "7070:7070"
    volumes:
      - redis1_data:/data
    command: redis-server --port 7070 --appendonly yes

  redis2:
    image: redis:7
    ports:
      - "7071:7071"
    volumes:
      - redis2_data:/data
    command: redis-server --port 7071 --appendonly yes

  # redis3:
  #   image: redis:7
  #   ports:
  #     - "6381:7072"
  #   volumes:
  #     - redis3_data:/data
  #   command: redis-server --appendonly yes

volumes:
  redis1_data:
  redis2_data: